model:
  name: test-model
  author: Krzysztof Piesiewicz
  short_description: Poisson GLM for average number of claims
  full_description: GLM from stats models with Poisson link function
  target: frequency # 'frequency' or 'severity'
  type: GLM


data:
  claims_freq_target_col: ClaimFreq_TRG
  claims_severity_target_col: ClaimAmount_TRG
  policy_id_col: IdPol
  split_random_seed: 1
  calib_size: 0.2 # the part of policies used for model calibration
  backtest_size: 0.2 # the part of policies used for backtest
  # => smpl_datasize = 1 - calib_data_size - calib_data_size


sampling:
  random_seed: 1
  n_obs: 54000 # 54k # the number of samples which are used to train a model
  target_ratio: 0.5 # the ratio of nonzero samples
  include_zeros: True # include zero values of target in a sample
  lower_bound: 0
  upper_bound: 100


data_engineering:
  random_seed: 1
  n_features: 100 # an integer or 'all'


data_science:
  model_random_seed: 1
  split_random_seed: 1
  test_size: 0.3


calibration:
  method: pure # the method of calibrating predicted values
  lower_bound:
  upper_bound: 1000


backtest:
  lower_bound:
  upper_bound: 1000
